name: Lint

on:
  pull_request:
    branches: ['main']
  workflow_call:

jobs:
  lint:
    name: Mago
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Mago
        uses: nhedger/setup-mago@v2

      - name: Lint
        run: mago lint
